# Generated by Django 3.1.4 on 2021-01-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='userRoot',
            field=models.CharField(default='unrooted', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='userName',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
