# Generated by Django 3.1.4 on 2021-01-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seq',
            name='userName',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
