# Generated by Django 3.1.4 on 2021-01-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0002_auto_20210106_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seq',
            old_name='user_run',
            new_name='user_nun',
        ),
    ]
