# Generated by Django 3.1.4 on 2021-01-08 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seq', '0003_auto_20210106_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seq',
            name='seq',
        ),
        migrations.RemoveField(
            model_name='seq',
            name='user_nun',
        ),
        migrations.AddField(
            model_name='seq',
            name='date',
            field=models.DateField(default=datetime.date(2021, 1, 8)),
        ),
        migrations.AddField(
            model_name='seq',
            name='end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seq',
            name='roomID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seq',
            name='start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seq',
            name='user_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seq',
            name='userName',
            field=models.EmailField(max_length=254),
        ),
    ]
