# Generated by Django 3.1.4 on 2021-01-06 08:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='end_time',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='start_time',
        ),
        migrations.AddField(
            model_name='room',
            name='classID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='roomID',
            field=models.IntegerField(unique=True),
        ),
    ]
