# Generated by Django 3.1.4 on 2021-01-08 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='room',
            name='start_time',
        ),
        migrations.AddField(
            model_name='room',
            name='date',
            field=models.DateField(default=datetime.date(2021, 1, 8)),
        ),
        migrations.AddField(
            model_name='room',
            name='end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='purpose',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='start',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='seq',
            field=models.IntegerField(default=0),
        ),
    ]
