# Generated by Django 3.1.4 on 2021-01-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20210106_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='classID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='seq',
            field=models.IntegerField(),
        ),
    ]
