# Generated by Django 3.1.4 on 2021-01-06 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_remove_room_classid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='date',
            field=models.DateField(default=datetime.date(2021, 1, 7)),
        ),
    ]
